apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: voting-app  # Replace 'default' with your desired namespace
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql







# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   namespace: ${NAMESPACE}
# spec:
#   ports:
#   - port: 3306
#     targetPort: 3306
#   selector:
#     app: mysql
#   clusterIP: None

